name: Create issues from code scanning results

on:
  workflow_dispatch:
  schedule:
  - cron: "30 1 * * *"

jobs:
  issue-creation:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    
    # Call Code Scanning API to get all Code Scanning Results since last pull
    - name: Get Code Scanning Results
      uses: JamesIves/fetch-api-data-action@releases/v1
      with:
        ENDPOINT: https://api.github.com/repos/get-secure/node-plugin/code-scanning/alerts
        # The configuration contains secrets held in the Settings/Secrets menu of the repository.
        CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer abcd"} }'
        # Once the token endpoint has fetched then this endpoint is requested.
        # ENDPOINT: https://example.com/data
        # The bearer token here is returned from the TOKEN_ENDPOINT call. The returned data looks like so: {data: {access_token: '123'}}, meaning it can be accessed using the triple bracket syntax.
        # CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer {{{ data.access_token }}}"} }'
    
    - name: Set selected color
      run: echo '::set-env name=API_DATA::$FETCH_API_DATA'
    
    - name: Get color
      run: echo 'The selected color is' $API_DATA
          
    - run: echo $FETCH_API_DATA
    
    # Create issue
    
    # To do
    # Make token_endpoint path dynamic
