name: Create issues from code scanning results

on:
  workflow_dispatch:
  schedule:
  - cron: "30 1 * * *"

jobs:
  issue-creation:

    runs-on: ubuntu-latest

    steps:
    
    #- name: Checkout repository
    #  uses: actions/checkout@v2
    #  with:
    #    # We must fetch at least the immediate parents so that if this is
    #    # a pull request then we can checkout the head.
    #    fetch-depth: 2
    
    - name: Get code scanning alerts
      uses: octokit/request-action@v2.x
      id: get_repo_alerts
      with:
        route: GET /repos/:repository/code-scanning/alerts
        repository: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create issue from code scanning alerts
      uses: maxkomarychev/oction-create-issue@v0.7.1
      id: create_issues
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Test
        body: ${{ steps.get_repo_alerts.outputs.data }}
  
    - name: Print outputs
      run: |
        echo ${{ steps.create_issues.outputs.id }}
        echo ${{ steps.create_issues.outputs.number }}
    
    
   
